In [1]:
import pandas as pd

## 2 main datatypes

In [2]:
series = pd.Series(["BMW","Toyata","Honda"])

In [3]:
series

0       BMW
1    Toyata
2     Honda
dtype: object

In [4]:
# Series = 1-dimensional

In [5]:
colours = pd.Series(["Red","Blue","White"])
colours

0      Red
1     Blue
2    White
dtype: object

In [6]:
# DataFrame = 2-dimensional
car_data = pd.DataFrame({"Car make":series,"Colour":colours})
car_data

  Car make Colour
0      BMW    Red
1   Toyata   Blue
2    Honda  White

In [7]:
# Import Data
car_sales = pd.read_csv('car-sales.csv')
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [8]:
# Exporting a dataframe

In [11]:
car_sales.to_csv("Exported-car-sales.csv",index=False)

In [12]:
exported_car_sales = pd.read_csv("Exported-car-sales.csv")
exported_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

## Describing data

In [14]:
# Attribute
car_sales.dtypes

# Function
#car_sales.to_csv()

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [15]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [16]:
car_columns = car_sales.columns
car_columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [18]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [19]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [20]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [21]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [27]:
car_prices = pd.Series([3000,1500,111250])

In [28]:
car_prices.mean()

np.float64(38583.333333333336)

In [29]:
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [30]:
car_sales["Doors"].sum()

np.int64(40)

In [31]:
len(car_sales)

10

## Viewing and selecting data

In [32]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [33]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [34]:
car_sales.head(7)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00

In [35]:
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [37]:
# .loc and .iloc
animals = pd.Series(["Cat","Dog","Snake","Bird","Panda"],index=[0,3,9,8,3])
animals

0      Cat
3      Dog
9    Snake
8     Bird
3    Panda
dtype: object

In [38]:
animals.loc[3]

3      Dog
3    Panda
dtype: object

In [39]:
animals.iloc[3]

'Bird'

In [41]:
animals.loc[9]

'Snake'

In [42]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [46]:
# .iloc refers to position
car_sales.iloc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [47]:
# .loc refers to index
car_sales.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [48]:
animals.iloc[:3]

0      Cat
3      Dog
9    Snake
dtype: object

In [49]:
car_sales.loc[:3]

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

In [52]:
car_sales["Make"]

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

In [56]:
car_sales["Colour"]

0    White
1      Red
2     Blue
3    Black
4    White
5    Green
6     Blue
7     Blue
8    White
9    White
Name: Colour, dtype: object

In [57]:
car_sales.Make

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

In [59]:
car_sales[car_sales["Make"] == "Toyota"]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
2  Toyota   Blue          32549      3  $7,000.00
5  Toyota  Green          99213      4  $4,500.00
8  Toyota  White          60000      4  $6,250.00

In [61]:
car_sales[car_sales["Odometer (KM)"] > 100000]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00