DOT PRODUCT

In [5]:
import numpy as np

In [6]:
import random

In [3]:
np.random.seed(0)

In [4]:
mat1 = np.random.randint(10, size=(5,3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [5]:
mat2 = np.random.randint(10, size=(5,3))
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [6]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [7]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [8]:
mat1 * mat2 # Element wise multiplication (Hadamard product)

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [9]:
# Dot product
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [10]:
# Transpose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [12]:
mat1.T.shape, mat2.shape

((3, 5), (5, 3))

In [13]:
mat3 = np.dot(mat1,mat2.T)

In [14]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [16]:
mat3.shape

(5, 5)

In [19]:
np.dot(mat1.T,mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [20]:
mat1.shape,mat2.shape

((5, 3), (5, 3))

In [21]:
## Dot product example

In [22]:
np.random.seed(0)

In [7]:
sales_amount = np.random.randint(20, size=(5,3))

In [8]:
sales_amount

array([[ 2,  2,  9],
       [ 1,  2,  9],
       [15,  9, 14],
       [16,  3,  8],
       [11, 18, 12]])

In [10]:
# Creates weekly_sales dataframe
import pandas as pd

weekly_sales = pd.DataFrame(sales_amount, index=['mon','Tue','Wed','Thu','Fri'],
                           columns = ['Almond butter','Peanut butter','Cashew butter'])

In [11]:
weekly_sales

     Almond butter  Peanut butter  Cashew butter
mon              2              2              9
Tue              1              2              9
Wed             15              9             14
Thu             16              3              8
Fri             11             18             12

In [12]:
# Create prices array
prices = np.array([10,8,12])

In [13]:
prices

array([10,  8, 12])

In [15]:
# Create butter_prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3), index=['Price'],columns=['Almond butter','Peanut butter','Cashew butter'])
butter_prices

       Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [16]:
prices

array([10,  8, 12])

In [17]:
total_sales = prices.dot(sales_amount)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [18]:
# Shape aren't alligned, lets transpose
total_sales = prices.dot(sales_amount.T)

In [19]:
total_sales

array([144, 134, 390, 280, 398])

In [22]:
# Create daily sales
butter_prices.shape

(1, 3)

In [23]:
weekly_sales.shape

(5, 3)

In [24]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [25]:
daily_sales

       mon  Tue  Wed  Thu  Fri
Price  144  134  390  280  398

In [27]:
weekly_sales

     Almond butter  Peanut butter  Cashew butter
mon              2              2              9
Tue              1              2              9
Wed             15              9             14
Thu             16              3              8
Fri             11             18             12

In [28]:
# Dosent work, not the right shape
weekly_sales["Total ($)"] = daily_sales
weekly_sales

ValueError: Cannot set a DataFrame with multiple columns to the single column Total ($)

In [29]:
weekly_sales["Total ($)"] = daily_sales.T

In [30]:
weekly_sales

     Almond butter  Peanut butter  Cashew butter  Total ($)
mon              2              2              9        144
Tue              1              2              9        134
Wed             15              9             14        390
Thu             16              3              8        280
Fri             11             18             12        398

Comparison operators

In [31]:
a1

NameError: name 'a1' is not defined

In [34]:
a1 = np.random.randint(10,size=(1,3))

In [35]:
a1

array([[9, 2, 4]])

In [36]:
a2 = np.random.randint(10,size=(2,3))

In [37]:
a2

array([[4, 3, 3],
       [0, 1, 5]])

In [38]:
a2 > a1

array([[False,  True, False],
       [False, False,  True]])

In [39]:
a1 > a2

array([[ True, False,  True],
       [ True,  True, False]])

In [40]:
a1 >= a2

array([[ True, False,  True],
       [ True,  True, False]])

In [42]:
type(a1 >= a2), (a1>a2).dtype

(numpy.ndarray, dtype('bool'))

In [43]:
a1 < 10

array([[ True,  True,  True]])

In [44]:
a1<1

array([[False, False, False]])

In [45]:
a2<3

array([[False, False, False],
       [ True,  True, False]])

In [46]:
a2

array([[4, 3, 3],
       [0, 1, 5]])

In [47]:
 a1 == a2

array([[False, False, False],
       [False, False, False]])

In [48]:
a1 == a1

array([[ True,  True,  True]])

In [49]:
a2

array([[4, 3, 3],
       [0, 1, 5]])

In [50]:
a1 != a2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [51]:
a2 / 2

array([[2. , 1.5, 1.5],
       [0. , 0.5, 2.5]])

In [52]:
a2 % 2

array([[0, 1, 1],
       [0, 1, 1]])

In [53]:
a2 % 3

array([[1, 0, 0],
       [0, 1, 2]])

In [54]:
a2 % 1

array([[0, 0, 0],
       [0, 0, 0]])

In [55]:
a2 ** 3

array([[ 64,  27,  27],
       [  0,   1, 125]])

In [56]:
a2

array([[4, 3, 3],
       [0, 1, 5]])

5. Sorting arrays

In [59]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[7, 1, 6, 0, 3],
       [9, 4, 9, 0, 1],
       [0, 8, 3, 5, 7]])

In [60]:
random_array.shape

(3, 5)

In [63]:
np.sort(random_array)

array([[0, 1, 3, 6, 7],
       [0, 1, 4, 9, 9],
       [0, 3, 5, 7, 8]])

In [64]:
np.argsort(random_array)

array([[3, 1, 4, 2, 0],
       [3, 4, 1, 0, 2],
       [0, 2, 3, 4, 1]])

In [65]:
np.argsort(a1)

array([[1, 2, 0]])

In [66]:
a1

array([[9, 2, 4]])

In [67]:
np.argmin(a1)

np.int64(1)

In [68]:
np.argmax(a2)

np.int64(5)

In [69]:
a2

array([[4, 3, 3],
       [0, 1, 5]])

In [71]:
a3 = np.random.randint(10,size=(3,5))

In [72]:
a3

array([[8, 3, 2, 0, 8],
       [8, 4, 3, 6, 4],
       [4, 1, 5, 6, 2]])

In [73]:
np.argmax(a3,axis=0)

array([0, 1, 2, 1, 0])

In [74]:
np.argmax(a3,axis=1)

array([0, 0, 3])

In [88]:
d = np.random.randint(10,size=(2,3,5))
d

array([[[8, 9, 5, 9, 1],
        [1, 0, 0, 9, 0],
        [1, 0, 9, 9, 8]],

       [[8, 5, 1, 1, 3],
        [0, 0, 3, 6, 3],
        [0, 0, 4, 4, 6]]])

In [89]:
np.argmax(d,axis=0)

array([[0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0]])

In [90]:
np.argmax(d,axis=1)

array([[0, 0, 2, 0, 2],
       [0, 0, 2, 1, 2]])

In [91]:
np.argmax(d,axis=2)

array([[1, 3, 2],
       [0, 3, 4]])

In [85]:
np.argmax(np.random.randint(10,size=(2,3,5)),axis=0)

array([[1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0]])