In [2]:
print("Hello")

Hello

In [3]:
import numpy as np

## Datatypes and attributes

In [4]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])

In [5]:
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3],
               [4,5,6.5]])

In [8]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [9]:
type(a2)

numpy.ndarray

In [10]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
a3.dtype

dtype('int64')

In [13]:
a2.dtype

dtype('float64')

In [14]:
a1.shape
a2.shape
a3.shape

(2, 3, 3)

In [15]:
a2.shape

(2, 3)

In [16]:
a1.shape

(3,)

In [17]:
a1.ndim

1

In [18]:
a2.ndim

2

In [19]:
a3.ndim

3

In [20]:
a1.size

3

In [21]:
a2.size

6

In [22]:
a3.size

18

In [27]:
import pandas as pd
df = pd.DataFrame(a2)
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

In [29]:
import pandas as pd
df = pd.DataFrame(a1)
df

   0
0  1
1  2
2  3

## 2. Creating numpy arrays

In [4]:
import numpy as np
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [5]:
sample_array.dtype

dtype('int64')

In [6]:
ones = np.ones((2,3))

In [7]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
ones.dtype

dtype('float64')

In [11]:
zeros = np.zeros((2,3))

In [12]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [15]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[2, 3, 3, 5, 9],
       [3, 0, 5, 2, 6],
       [8, 9, 8, 8, 9]])

In [16]:
random_array.size

15

In [17]:
random_array.shape

(3, 5)

In [18]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.48604435, 0.86908977, 0.55073348],
       [0.87644735, 0.04566839, 0.72579481],
       [0.06002812, 0.92678224, 0.00787975],
       [0.96161669, 0.81424366, 0.86161455],
       [0.62854331, 0.04469712, 0.50181597]])

In [19]:
random_array_2.size

15

In [20]:
random_array_2.shape

(5, 3)

In [22]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.54775703, 0.56372465, 0.9554041 ],
       [0.69889319, 0.5406553 , 0.9042176 ],
       [0.0827172 , 0.34411696, 0.48244982],
       [0.86793058, 0.53187923, 0.42543335],
       [0.7150258 , 0.74486673, 0.8883945 ]])

In [47]:
# Pseudo-random numbers
np.random.seed(seed=9999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [48]:
random_array_4.shape

(5, 3)

In [2]:
np.random.seed(10)
random_array_5 = np.random.random((5,3))
random_array_5

NameError: name 'np' is not defined

In [3]:
import numpy as np

## 3. Different ways of viewing arrays and matrices

In [4]:
np.unique([0,1,2,3,3,3,32,2,2,1,])

array([ 0,  1,  2,  3, 32])

In [5]:
a1[0]

NameError: name 'a1' is not defined